apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v3"
spec:
  selector:  
    matchLabels:
       app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
        team: team-A
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v3 
        env:
        - name: DUMMY
          value: "8"
        ports:
        - name: "app-port"
          containerPort: 80       
