apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - http:
        paths: # <--- Indented by 2 spaces relative to "http"      
          - path: /user
            pathType: Prefix
            backend: 
              service:
                name: user-service
                port:
                  number: 80        
          - path: /  #can be kept in beginning also,kept here to avoid confusion.logic remains same.
            pathType: Prefix
            backend: 
              service:
                name: home-service
                port:
                  number: 80        