apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"
  application.properties: |
    appUrl= http://my-app-service
    timeout=30
    duration=1
    usrname='Joe'
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pod-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pod-volume
    persistentVolumeClaim:
      claimName: my-pvc

