apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: nginx1
    image: nginx
  - name: util
    image: vinsdocker/util  
    args:  # args: ["sleep","3600"]
    - "sleep"
    - "3600"
